name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Python deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          .venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: |
          ~/.local/share/uv
          ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('.uv/config.json') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        # create venv in repo so it can be cached
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        uv sync --dev

    - name: Run pre-commit
      run: uv run pre-commit run --all-files

    - name: Run tests with coverage
      run: |
        source .venv/bin/activate
        uv run pytest --cov --cov-branch --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
